-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 18:38:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS RailwayManagementDB;
CREATE DATABASE IF NOT EXISTS RailwayManagementDB;
USE RailwayManagementDB;
-- -----------------------------------------------------
-- Table `MobileDevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileDevice` ;

CREATE TABLE IF NOT EXISTS `MobileDevice` (
  `device_id` INT(10) NOT NULL,
  `brand_name` VARCHAR(10) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `email` VARCHAR(10) NULL,
  `device` INT(10) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `User_MobileDevice_FK_idx` (`device` ASC) ,
  CONSTRAINT `User_MobileDevice_FK`
    FOREIGN KEY (`device`)
    REFERENCES `MobileDevice` (`device_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Routes` ;

CREATE TABLE IF NOT EXISTS `Routes` (
  `route_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`route_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trip` ;

CREATE TABLE IF NOT EXISTS `Trip` (
  `trip_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `routes` INT(10) NULL,
  PRIMARY KEY (`trip_id`),
  INDEX `Trip_Routes_FK_idx` (`routes` ASC) ,
  CONSTRAINT `Trip_Routes_FK`
    FOREIGN KEY (`routes`)
    REFERENCES `Routes` (`route_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Train` ;

CREATE TABLE IF NOT EXISTS `Train` (
  `train_id` INT(10) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `trip` INT(10) NULL,
  PRIMARY KEY (`train_id`),
  INDEX `Train_Trip_FK_idx` (`trip` ASC) ,
  CONSTRAINT `Train_Trip_FK`
    FOREIGN KEY (`trip`)
    REFERENCES `Trip` (`trip_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PoliceDepartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PoliceDepartment` ;

CREATE TABLE IF NOT EXISTS `PoliceDepartment` (
  `p_station_id` INT(10) NOT NULL,
  `police_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`p_station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FireDepartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FireDepartment` ;

CREATE TABLE IF NOT EXISTS `FireDepartment` (
  `f_station_id` INT(10) NOT NULL,
  `firefighter_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`f_station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier` ;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `supplier_id` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainYard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainYard` ;

CREATE TABLE IF NOT EXISTS `TrainYard` (
  `t_yard_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `supplier` INT(10) NULL,
  PRIMARY KEY (`t_yard_id`),
  INDEX `TrainYard_Supplier_FK_idx` (`supplier` ASC) ,
  CONSTRAINT `TrainYard_Supplier_FK`
    FOREIGN KEY (`supplier`)
    REFERENCES `Supplier` (`supplier_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RepairYard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RepairYard` ;

CREATE TABLE IF NOT EXISTS `RepairYard` (
  `r_yard_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `supplier` INT(10) NULL,
  PRIMARY KEY (`r_yard_id`),
  INDEX `RepairYard_Supplier_FK_idx` (`supplier` ASC) ,
  CONSTRAINT `RepairYard_Supplier_FK`
    FOREIGN KEY (`supplier`)
    REFERENCES `Supplier` (`supplier_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ticket` ;

CREATE TABLE IF NOT EXISTS `Ticket` (
  `ticket_id` INT(10) NOT NULL,
  `exp_id` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `train` INT(10) NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `Ticket_Train_FK_idx` (`train` ASC) ,
  CONSTRAINT `Ticket_Train_FK`
    FOREIGN KEY (`train`)
    REFERENCES `Train` (`train_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Passenger` ;

CREATE TABLE IF NOT EXISTS `Passenger` (
  `passenger_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `ticket` INT(10) NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`passenger_id`),
  INDEX `Passenger_Ticket_FK_idx` (`ticket` ASC) ,
  CONSTRAINT `Passenger_Ticket_FK`
    FOREIGN KEY (`ticket`)
    REFERENCES `Ticket` (`ticket_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `manager_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Station` ;

CREATE TABLE IF NOT EXISTS `Station` (
  `station_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `fire_dept` INT(10) NULL,
  `police_dept` INT(10) NULL,
  `t_yard` INT(10) NULL,
  `r_yard` INT(10) NULL,
  `region` INT(10) NOT NULL,
  `passenger` INT(10) NULL,
  `manager` INT(10) NULL,
  PRIMARY KEY (`station_id`),
  INDEX `Station_PoliceDepartment_FK_idx` (`police_dept` ASC) ,
  INDEX `Station_FireDepartment_FK_idx` (`fire_dept` ASC) ,
  INDEX `Station_TrainYard_FK_idx` (`t_yard` ASC) ,
  INDEX `Station_RepairYard_FK_idx` (`r_yard` ASC) ,
  INDEX `Station_Region_FK_idx` (`region` ASC) ,
  INDEX `Station_Passenger_FK_idx` (`passenger` ASC) ,
  INDEX `Station_Manager_FK_idx` (`manager` ASC) ,
  CONSTRAINT `Station_PoliceDepartment_FK`
    FOREIGN KEY (`police_dept`)
    REFERENCES `PoliceDepartment` (`p_station_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Station_FireDepartment_FK`
    FOREIGN KEY (`fire_dept`)
    REFERENCES `FireDepartment` (`f_station_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Station_TrainYard_FK`
    FOREIGN KEY (`t_yard`)
    REFERENCES `TrainYard` (`t_yard_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Station_RepairYard_FK`
    FOREIGN KEY (`r_yard`)
    REFERENCES `RepairYard` (`r_yard_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Station_Region_FK`
    FOREIGN KEY (`region`)
    REFERENCES `Region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Station_Passenger_FK`
    FOREIGN KEY (`passenger`)
    REFERENCES `Passenger` (`passenger_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Station_Manager_FK`
    FOREIGN KEY (`manager`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PaymentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentType` ;

CREATE TABLE IF NOT EXISTS `PaymentType` (
  `type_id` INT(10) NOT NULL,
  `billing_adress` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountType` ;

CREATE TABLE IF NOT EXISTS `AccountType` (
  `account_typeid` INT NOT NULL,
  `version` VARCHAR(10) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_typeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Driver` ;

CREATE TABLE IF NOT EXISTS `Driver` (
  `driver_id` INT(10) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT(10) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `station` INT(10) NOT NULL,
  `manager` INT(10) NULL,
  `driver` INT(10) NULL,
  INDEX `Employee_Station_FK_idx` (`station` ASC) ,
  INDEX `Employee_Manager_FK_idx` (`manager` ASC) ,
  INDEX `Employee_Driver_FK_idx` (`driver` ASC) ,
  CONSTRAINT `Employee_Station_FK`
    FOREIGN KEY (`station`)
    REFERENCES `Station` (`station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Employee_Manager_FK`
    FOREIGN KEY (`manager`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Employee_Driver_FK`
    FOREIGN KEY (`driver`)
    REFERENCES `Driver` (`driver_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT(10) NULL,
  `email` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `p_type` INT(10) NULL,
  `a_type` INT(10) NOT NULL,
  `user` INT(10) NOT NULL,
  `description` VARCHAR(45) NULL,
  INDEX `Account_Passenger_FK_idx` (`account_id` ASC) ,
  INDEX `Account_PaymentType_FK_idx` (`p_type` ASC) ,
  INDEX `Account_AccountType_FK_idx` (`a_type` ASC) ,
  INDEX `Account_User_FK_idx` (`user` ASC) ,
  CONSTRAINT `Account_Passenger_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Passenger` (`passenger_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Account_PaymentType_FK`
    FOREIGN KEY (`p_type`)
    REFERENCES `PaymentType` (`type_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Account_AccountType_FK`
    FOREIGN KEY (`a_type`)
    REFERENCES `AccountType` (`account_typeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Account_User_FK`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
